default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: agile-chess_development

test:
  <<: *default
  database: agile-chess_test

# For use with AWS RDS
production:
  <<: *default
  database: agile-chess_production
